config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :kondos, only: [:index, :new, :create, :destroy, :edit, :update, :reserve] do
    resources :favorites, only: [:create]
  end

  get 'kondos/random', to: 'kondos#random'

  get 'dashboard', to: 'dashboard#show', as: :dashboard

  resources :favorites, only: [:destroy]

  # get '/split', to: 'pages#split'


  post '/dashboard/kondo_update', to: 'kondos#reserve'


  resources :chatrooms, only: [:show, :create] do

    resources :messages, only: [:create]
  end

  get '/dashboard/kondo_reserve', to: 'kondos#reserve'
  get '/dashboard/kondo_active', to: 'kondos#active'

  mount ActionCable.server => "/cable"
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @kondos = current_user.kondos
    @favorites = current_user.favorites
    @chatrooms = Chatroom.where(user_id: current_user.id )
    #map all users kondos to array of ids
    ids = @kondos.map { |k|  k.id }
    # query DB to find all chatrooms where my items are the subject
    @chatrooms_my_item = Chatroom.where(kondo_id: ids )
    #merge @chatrooms with @chatrooms_my_item == combined active record association 
    @chatrooms = @chatrooms.or(@chatrooms_my_item)
    authorize :dashboard, :show?
  end
end

app/views/dashboard/index.html.erb
<div class="dash-container">
  <p class="dashboard-header">Dashboard</p>
  <div class="boxes">
    <div class="dash-box">
      <div class="box-content">
      <p>My Favorites</p>
        <% @favorites.each do |fav| %>
       <h1 class="kondo-title"><i class="fas fa-heart"></i>  <%= fav.kondo.title %></h1>
        <%= link_to 'Unfavorite', favorite_path(fav), method: :delete %>
        <%= link_to 'Message Kondonator'%>
        <% end %>
      </div>
    </div>
    <div class="dash-box">
      <div class="box-content">
      <p>My Messages</p>
      </div>
    </div>
    <div class="dash-box">
      <div class="box-content">
        <p>My Kondos</p>
        <% @kondos.each do |kondo|%>
          <div class="kondo">
            <h1 class="kondo-title"><i class="fas fa-gem"></i>  <%= kondo.title %></h1>
            <p class="kondo-desc"><%= kondo.description %></p>
            <% if kondo.reserved %>
              <p class="kondo-status">- This item is reserved</p>
              <% else %>
              <p class="kondo-status">- This item is not yet reserved</p>
            <% end %>
            <% if kondo.active %>
              <p class="kondo-status">- Your Kondo is active</p>
            <% end %>
            <%= link_to "button", dashboard_kondo_update_path(:kondo_id => kondo.id), method: :post %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/dashboard/show.html.erb
<div class="dash-container">
  <p class="dashboard-header">Dashboard</p>
  <div class="headers-dash">
    <h2 class="box-headers">My Favorites</h2>
    <h2 class="box-headers">My Messages</h2>
    <h2 class="box-headers">My Kondos</h2>
  </div>
  <div class="boxes">
    <div class="dash-box">
      <div class="box-content">
        <% @favorites.each do |fav| %>
          <div class="card-product-two">
            <% if fav.kondo.image.attached? %>
              <%= cl_image_tag fav.kondo.image.key, height: 180, width: 100, crop: :fill %>
            <% end %>
              <div class="card-product-infos-dash">
                <div id="fav-icon">
                  <h2><%= fav.kondo.title %></h2>
                  <%= link_to favorite_path(fav, redirect_to: "dashboard"), method: :delete do %>
                    <i data-toggle="tooltip" data-placement="top" title="Unfavorite Kondo" class="fas fa-heart mr-2"></i>
                  <% end %>
                </div>
                <p><%= fav.kondo.description %></p>
                <div class="card-product-seller-dash">
                  <div class="location-grid-dash">
                    <p><i class="fas fa-map-marker-alt"></i>
                    <%= fav.kondo.location %></p>
                  </div>
                  <%= form_tag chatrooms_path, method: :post do %>
                    <%= hidden_field_tag :kondo_id, fav.kondo.id %>
                    <%= submit_tag "Contact Kondor", class: "btn btn-main-grid btn-contact-grid-dash" %>
                <% end %>
                </div>
            </div>
          </div>
        <% end %>
          <%= link_to kondos_path do  %>
          <div class="empty">
            <i class="fas fa-plus"></i>
          </div>
          <% end %>
      </div>
    </div>

    <div class="dash-box">
      <div class="box-content">
        <% @chatrooms.each do |chatroom| %>
        <%= link_to chatroom_path(chatroom.id) do %>
          <div class="chats">
            <% if chatroom.kondo.image.attached? %>
              <%= cl_image_tag chatroom.kondo.image.key, height: 180, width: 100, crop: :fill %>
            <% end %>
            <div>
            <% if chatroom.kondo.user.id == current_user.id %>
            <% end %>
              <p class="chat-buddy"><%= chatroom.kondo.user.username %> </p>
              <p class="chat-title"><%= chatroom.kondo.title %></p>
              <p class="chat-content">Last message: <%= chatroom.updated_at.day %>.<%= chatroom.updated_at.month %>.<%= chatroom.updated_at.year %></p>
            </div>
          </div>
          <% end %>
        <% end %>
        </div>
      </div>


    <div class="dash-box">
      <div class="box-content">
        <% @kondos.each do |kondo|%>
        <div class="card-product-three">
            <% if kondo.image.attached? %>
              <%= cl_image_tag kondo.image.key, height: 180, width: 100, crop: :fill %>
            <% end %>
            <div class="card-product-infos-dash">
              <div id="fav-icon">
                <h2 class="card-product-header-white"><%= kondo.title %></h2>
                <% if policy(kondo).destroy? %>
                  <%= link_to kondo_path(kondo), method: :delete, data: {confirm: 'Are you sure you want to delete this Kondo?'} do %>
                  <i class="fas fa-times"></i>
                  <% end %>
                <% end %>
              </div>
              <p class="card-product-desc"><%= kondo.description %></p>
              <div class="icons">
                <% if kondo.reserved %>
                  <%= link_to dashboard_kondo_reserve_path(:kondo_id => kondo.id) do %>
                  <i data-toggle="tooltip" data-placement="top" title="Reserved Kondo" class="fas fa-toggle-on"></i>
                  <% end %>
                  <% else %>
                    <%= link_to dashboard_kondo_reserve_path(:kondo_id => kondo.id) do %>
                    <i data-toggle="tooltip" data-placement="top" title="Reserve Kondo" class="fas fa-toggle-off"></i>
                    <% end %>
                <% end %>
                <% if kondo.active %>
                  <%= link_to dashboard_kondo_active_path(:kondo_id => kondo.id) do %>
                  <i data-toggle="tooltip" data-placement="top" title="Deactivate Kondo" class="far fa-eye"></i>
                <% end %>
                <% else %>
                  <%= link_to dashboard_kondo_active_path(:kondo_id => kondo.id) do %>
                  <i data-toggle="tooltip" data-placement="top" title="Activate Kondo" class="far fa-eye-slash"></i>
                  <% end %>
                <% end %>
                <%= link_to edit_kondo_path(kondo) do %>
                  <i data-toggle="tooltip" data-placement="top" title="Edit Kondo" class="far fa-edit"></i>
                <% end %>
              </div>
            </div>
          </div>
      <% end %>
        <%= link_to new_kondo_path do  %>
        <div class="empty">
          <i class="fas fa-plus"></i>
        </div>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>