config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :kondos, only: [:index, :new, :create, :destroy, :edit, :update, :reserve] do
    resources :favorites, only: [:create]
  end

  get 'kondos/random', to: 'kondos#random'

  get 'dashboard', to: 'dashboard#show', as: :dashboard

  resources :favorites, only: [:destroy]

  # get '/split', to: 'pages#split'


  post '/dashboard/kondo_update', to: 'kondos#reserve'


  resources :chatrooms, only: [:show, :create] do

    resources :messages, only: [:create]
  end

  get '/dashboard/kondo_reserve', to: 'kondos#reserve'
  get '/dashboard/kondo_active', to: 'kondos#active'

  mount ActionCable.server => "/cable"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    <a href="#">About Us</a>
  </div>
  <div class="footer-copyright">
    <a href="#">Customer Support</a>
  </div>
  <div class="footer-copyright">
    <a href="#">User Policy</a>
  </div>
</div>

app/views/shared/_grid-card.html.erb
<div class="card-product" id=<%="kondo-index-#{kondo.id}"%>>
  <% if kondo.image.attached? %>
    <%= cl_image_tag kondo.image.key, height: 400, width: 400, crop: :fill %>
  <% end %>
    <div class="card-product-infos">
        <h2><%= kondo.title %></h2>
        <p><%= kondo.description %></p>
        <% if policy(kondo).destroy? %>
          <%= link_to "delete kondo", kondo_path(kondo), method: :delete, data: {confirm: 'Are you sure you want to delete?'} %></p>
        <% end %>
        <% if current_user %>
          <% if !current_user.owner?(kondo) %>
            <% if current_user.favorite?(kondo) %>
              <%= link_to favorite_path(Favorite.find_by(kondo: kondo), :location => params[:location], :kondo_id => kondo.id), method: :delete, remote: true do %>
              <i class="fas fa-heart"></i>
              <% end %>
            <% else %>
              <%= link_to kondo_favorites_path(kondo, :location => params[:location]), method: :post, remote: true do %>
              <i class="far fa-heart"></i>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <div class="card-product-seller">
        <p><strong>Kondor:</strong> <%= kondo.user.username %></p>
        <p><strong>Pickup at:</strong> <%= kondo.location %></p>
      </div>
    </div>

  </div>
  _______________

  <div class="container mt-5">
    <h5 style="font-weight: bold">Kondos nearby</h5>
    <p style="font-size: 14px; color: white">Browse through the things other people in your neighborhood don't need anymore.</p>
    <div class="kondos-container">
      <% @kondos.each do |kondo| %>
      <div class="card-product" id=<%="kondo-index-#{kondo.id}"%> >
        <% if kondo.image.attached? %>
          <%= cl_image_tag kondo.image.key, height: 400, width: 400, crop: :fill %>
        <% end %>
          <div class="card-product-infos">
            <h2><%= kondo.title %></h2>
            <p><%= kondo.description %></p>
              <% if current_user && !current_user.owner?(kondo) %>
                <% if current_user.favorite?(kondo) %>
                  <%= link_to favorite_path(Favorite.find_by(kondo: kondo), :location => params[:location], :kondo_id => kondo.id), method: :delete, remote: true do %>
                  <i class="fas fa-heart"></i>
                  <% end %>
                <% else %>
                  <%= link_to kondo_favorites_path(kondo, :location => params[:location]), method: :post, remote: true do %>
                  <i class="far fa-heart"></i>
                  <% end %>
                <% end %>
              <% elsif current_user && current_user.owner?(kondo) %>
                  <%# if user is logged in and is the owner she sees nothing %>
              <% else %>
                <%= link_to kondo_favorites_path(kondo, :location => params[:location]), method: :post do %>
                  <i class="far fa-heart"></i>
                <% end %>
              <% end %>
          <div class="card-product-seller">
            <p><strong>Kondor:</strong> <%= kondo.user.username %></p>
            <p><strong>Pickup at:</strong> <%= kondo.location %></p>
          </div>
        </div>
      </div>
      <% end %>
  >>>>>>> master
    </div>
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm kondo-nav fixed-top">
  <!-- <a href="/" class="kondo-link"><strong>Kondo</strong>Kondo</a> -->
  <%= link_to image_tag('logo_small.png', :width=>90), root_path %>
  <span id="open"><i class="fas fa-bars"></i></span>
  <div id="mySidenav" class="sidenav">
    <div class="upper">
      <a class="closebtn" id="close">&times;</a>
      <a href="/">Home</a>
      <% if user_signed_in? %>
        <a href="/dashboard">Dashboard</a>
        <a href="/kondos/new">Make a Kondo</a>
        <%= link_to "Logout", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Login",  new_user_session_path%>
      <% end %>
    </div>
    <div class="footer">
      <div class="footer-copyright">
        <a class='footer-words' href="#">About Us</a>
        <a class='footer-words' href="#">User Policy</a>
        <a class='footer-words' href="#">Customer Support</a>
      </div>
      <div class="footer-links">
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
      </div>
    </div>
  </div>
</div>